### PR TITLE
[ITG-95] Update styles of task list and task form according to the design

### PR DESCRIPTION
**Pull request by john-sonz**
Updated styling of task creation and edition form, task list, and the done checkbox.

---

#### Resources

[ITG-95](https://kulawska.atlassian.net/browse/ITG-95)

### CODE REVIEW

**Review by koszar91 — COMMENTED** [review]
Some minor visual issues:
- in create new task form inputs has font that is not really clear; it should be thicker or maybe darker
- rounded corners in general could be more rounded, according to mockup :3

**Comment by koszar91** [comment]
Little bug: after submitting newly-done task we're not redirected to the home page.

**Comment by john-sonz** [comment]
> in create new task form inputs has font that is not really clear; it should be thicker or maybe darker

What do you mean it's not clear? It's literally black, can't get darker than that xD

image


> rounded corners, in general, could be more rounded, according to the mockups :3

I wouldn't go too far with rounding, too much of it starts looking a bit ridiculous, and we should have different levels of rounding for different types of elements.

**Comment by koszar91** [comment]
The thing is it's the operating system difference, i guess.
image
I think you should make it a bit more consistent, if possible.
Another examples:
image
Up to me it is not our font.

**Comment by john-sonz** [comment]
@koszar91 I updated the font family to be the same as in Figma, and the same across all OS.

**Review by koszar91 — APPROVED** [review]
Perfect! There is a big difference with this font change, now it actually looks beautiful!

**Pull request merged**
